### ISSUE TITLE
Wrong MIME type for mp3 subjects

### ISSUE THREAD

**Issue by srallen** [zooniverse/panoptes-python-client#123] opened 2017-09-07 20:46 UTC
Related to zooniverse/Panotpes#2458, @trouille reports
> When I try with the Panoptes Python Client and the script at this [link](https://drive.google.com/file/d/0BzeL_TYT7IYPWUgwUmVFekszNTA/view?usp=sharing), I get the error:
panoptes_client.panoptes.PanoptesAPIException: Validation failed: Locations is invalid

Rails does not recognize `audio/mp3` as a valid MIME type. For mp3s, the MIME type needs to be `audio/mpeg`. `magic` is likely detecting the wrong MIME type for these files.

**Comment by srallen** [comment] 2017-09-07 20:54
`magic` appears to be detecting mp3s as `audio/x-wav`

**Comment by astopy** [comment] 2017-10-13 14:14
I'm not able to reproduce this here.

```python
>>> f = open('/Users/adam/Desktop/file.mp3', 'rb')
>>> magic.from_buffer(f.read(), mime=True)
'audio/mpeg'
>>> f.close()
>>> from panoptes_client import Panoptes, Project, Subject
>>> Panoptes.connect([...])
<panoptes_client.panoptes.Panoptes object at 0x7f4187443208>
>>> p = Project(7)
>>> s = Subject()
>>> s.links.project=p
>>> s.add_location('/Users/adam/Desktop/file.mp3')
>>> s.save()
>>>
```

**Comment by eatyourgreens** [comment] 2017-10-13 14:16
From memory, the issue was the specific files that were being uploaded. The extension was .mp3, but they were actually WAV files.

**Comment by astopy** [comment] 2017-10-13 14:16
Ah ok, in that case I'll close this.

**Closed by astopy** 2017-10-13 14:16 UTC
Labels: release/1.0
