### ISSUE TITLE
NfN Org related stats request

### ISSUE THREAD

**Issue by trouille** [zooniverse/panoptes-python-client#216] opened 2019-04-26 16:40 UTC
Notes from Nature will launch its organization (https://lab.zooniverse.org/organizations/16) in May. In November we have dev time set aside to create an Org 'stats' page. 

We're hoping in the interim (between May and November) that it wouldn't be too time-consuming to write a script that Michael could run himself that provides him the stats listed below. He uses these stats to support, encourage, keep tabs on the different institutions using NfN to unlock their data. 

The stats he uses are the following:

- Workflow ID
- Workflow name
- Workflow start date (or a proxy such as first transcription or, the least ideal, the 'created at' date from the workflow_resources)
- Workflow end date, if the workflow is complete (workflow_resources has a 'finished at' date)
- Total number of subjects associated with the workflow (best if this can be all the subjects to date that have been linked, even if currently unlinked. Understandable if only possible to provide the number for currently linked subjects)

Note - it'll be onerous if Michael needs to rerun the script 20 times for the eventual 20+ different workflows that will be linked through different projects over the summer to his Org. So ideally the script just loops through all the different workflows of projects associated with the NfN Organization (see https://lab.zooniverse.org/organizations/16). 

In case it helps make the script easier to write -- we could have Michael maintain a .csv file with a list of all the workflow IDs (i.e., it would be up to him to add new workflow IDs every time he adds a new workflow to the Org). The script would reference this .csv file to loop through all the needed workflows. Just noting this so we don't spend lots of time trying to automate a piece that Michael could maintain manually relatively easily. 

It may be that I should post this in the python client repo - just let me know.

**Comment by adammcmaster** [comment] 2019-04-30 10:44
Sure, this should be pretty straightforward to implement.

**Comment by adammcmaster** [comment] 2019-05-03 11:38
This script will do it: https://gist.github.com/adammcmaster/605695db28d73a88c9020fe1da53c72d

**Comment by trouille** [comment] 2019-05-03 14:45
Thanks @adammcmaster! 

Could you create two additional simple variants of this same script? 

1) One variant is a script that reads in a list of workflow IDs (rather than pulling all workflows from all currently linked projects to an Org) -- Michael will create and maintain that list of workflow IDs (as a simple .csv file). The reason is that projects will link and then unlink from the Notes from Nature Organization, but he's going to want to have a comprehensive list of all projects' workflows that have been linked at one point over time to the NfN Org. It'll be great to keep this current script so he can run it on all currently linked projects. I also foresee this could be a useful script for other teams. (We'll add it to the data-digging repo)

2) A second variant is a script that reads in a list of project IDs (rather than only looping through projects currently linked to the Org). Again, Michael will maintain that list of project IDs. It's just for the scenario where it may actually be easier for him to just maintain a list of project IDs (rather than all the individual workflow IDs). Though there may be reasons he won't want to do this. I believe both these variants will be pretty simple to create, so easier to provide him the option (and also may prove a useful script for others; will add to data-digging repo). 

Thank you!

**Comment by adammcmaster** [comment] 2019-05-03 15:18
Sure, will do.

**Comment by denslowm** [comment] 2019-05-17 18:24
Thanks for this. I have a few questions so far.

1. When I run the script I get a list and then the following:

Traceback (most recent call last):
  File "org_workflow_stats.py", line 23, in <module>
    print("{}".format(project.display_name))
  File "/Users/michaeldenslow/panoptes/venv/lib/python2.7/site-packages/panoptes_client/panoptes.py", line 712, in __getattr__
    self.reload()
  File "/Users/michaeldenslow/panoptes/venv/lib/python2.7/site-packages/panoptes_client/panoptes.py", line 834, in reload
    reloaded_object = self.__class__.find(self.id)
  File "/Users/michaeldenslow/panoptes/venv/lib/python2.7/site-packages/panoptes_client/project.py", line 57, in find
    return cls.where(id=id, slug=slug).next()
  File "/Users/michaeldenslow/panoptes/venv/lib/python2.7/site-packages/panoptes_client/panoptes.py", line 672, in where
    return cls.paginated_results(*cls.http_get(_id, params=kwargs))
  File "/Users/michaeldenslow/panoptes/venv/lib/python2.7/site-packages/panoptes_client/panoptes.py", line 623, in http_get
    **kwargs
  File "/Users/michaeldenslow/panoptes/venv/lib/python2.7/site-packages/panoptes_client/panoptes.py", line 320, in get
    retry=retry,
  File "/Users/michaeldenslow/panoptes/venv/lib/python2.7/site-packages/panoptes_client/panoptes.py", line 281, in json_request
    json_response['errors']
panoptes_client.panoptes.PanoptesAPIException: Could not find project with id='9275'

2. When a try to write to a file 
`python org_workflow_stats.py >> stats`

I get a text file with only 5 results, but I was expecting all the workflows.

**Comment by trouille** [comment] 2019-05-17 18:36
@denslowm Could you share the text file that you do get, so we can see what projects do work. It's interesting that the error is Could not find project with id='9275', since https://www.zooniverse.org/lab/9275 does exist. But maybe due to that project being 'private' still? 

@adammcmaster is out today, but will be back on Monday. Hopefully when he returns he'll be able to look at this bug and also create the two variants of the script listed above (one that accepts the list of projects and one that accepts the list of workflows of interest).

**Comment by denslowm** [comment] 2019-05-17 18:51
Here is the file. 
[stats.txt](https://github.com/zooniverse/panoptes-python-client/files/3192700/stats.txt)

**Comment by adammcmaster** [comment] 2019-05-21 13:17
The could not find project error will be because the project is private/because the script isn't logging into the API. @denslowm did you insert your username/password into the script on lines 10 and 11?

I should hopefully be able to write the other two versions of the script in the next day or two.

**Comment by denslowm** [comment] 2019-05-21 23:24
I ran after inserting my credentials and get the following message:

(venv) BIO-02NK3RUG3QJ:panoptes michaeldenslow$ python org_workflow_stats_MD.py >> stats2.txt
No handlers could be found for logger "panoptes_client"
Traceback (most recent call last):
  File "org_workflow_stats_MD.py", line 30, in <module>
    workflow.display_name,
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2014' in position 117: ordinal not in range(128)

Also the output file contains information for 4 workflows.

**Comment by adammcmaster** [comment] 2019-05-24 15:30
Do you have access to Python 3? If so I think using that should fix the unicode error. If not I'll try and see if I can work around it.

I haven't been able to work on the two new versions of the script yet. It looks like it'll be next week now before I can do that.

**Comment by PmasonFF** [comment] 2019-05-24 15:49
A fix that works in both Python 2.7 and 3.7 is here - https://gist.github.com/PmasonFF/80601eadf23b6b1dde1ddf6f465c1edb
I am not sure what caused the message"No handlers could be found for logger "panoptes_client"
Without logging in to the panoptes client all projects except 9275 are listed, though many have no finished date.

**Comment by PmasonFF** [comment] 2019-05-28 23:47
Please see my latest attempt to add the functionality requested by Laura Trouille here:
https://github.com/PmasonFF/Zooniverse-data-digging/blob/master/Panoptes_client_examples/org_workflow_stats_expanded.py
with a readme file here:
https://github.com/PmasonFF/Zooniverse-data-digging/blob/master/Panoptes_client_examples/org_workflow_stats_expanded_readme.md

Adam please have a look and pass them on to Michael Denslowm or request changes as needed.

**Comment by adammcmaster** [comment] 2019-05-30 10:29
Thanks for that, @PmasonFF, it's really appreciated!

@denslowm Could you take a look at the readme and give @PmasonFF's script a try?

**Comment by denslowm** [comment] 2019-05-31 19:09
Hi All,

Sorry for the delay (I have been traveling) and thanks again for the help!

I'm afraid I may need some more hand holding here. I think the issue is around my username/password. 

It says "script assumed the user has their zooniverse credentials set up in their operating system varaibles as USERNAME and PASSWORD" How do I verify that?

I also tried changing those to my actual Zooniverse credentials, but then I got KeyError: then my username.

**Comment by PmasonFF** [comment] 2019-05-31 19:25
Hi!  
line 86 is Panoptes.connect(username=os.environ['User_name'], password=os.environ['Password'])
replace it with
Panoptes.connect(username='md68135', password='xxxxxx') where xxxxxx is your actual zooniverse password.
Failing that delete the line - you will get everything for organization 16 except for one private project 9275.
The problem with hardcoding your credentials is you have to take care not to share the script AND your password inadvertently!
Are you on Windows or Mac Or?? I may have instructions for setting up environmental variables you could follow??

**Comment by denslowm** [comment] 2019-05-31 19:52
Thanks! It seems I didn't remove the "os.environ" part the first time. When I hardcode in my credentials it works. Good point about sharing my password inadvertently!
I am on a Mac.

I have a few follow up questions now. 
What is Created date exactly? As Laura noted we want to get as close as we can to the time the expedition actually launched. 

How come several of the Finished dates are empty? It's hard to imagine that this many never reached 100%.

I think we might have an issue with the column names as Finished date shows up twice and subjects seems to be offset. 

I am realizing now that we are also going to need Retirement limit. Can that be added?

**Comment by PmasonFF** [comment] 2019-05-31 20:35
Re Created date. Yes the request was "Workflow start date (or a proxy such as first transcription or, the least ideal, the 'created at' date from the workflow_resources)"  The problem is the two ideal choices are not directly available in the API and Yes the created date is not a particularly good proxy as it it the date the workflow is first generated in Panoptes.
Options:  I will look to see If I can pull the first classification from the workflow but that will be almost as bad.... dating to the first test of the workflow... Projects have an attribute launch_date but I do not think workflows have anything like what we need  @adammcmaster any ideas?
Re Finished dates - are also fickle as there are a number of operations on the project that will reset them. Again I don't know of any better way to get a completion date, short of searching the subject sets for the latest retired date.  This would not be practical for a script that would run frequently over a large number of projects/workflows, but it may be practical to get better dates on a workflow basis where we know the workflow is likely complete and we only need to get the dates once and keep them.

Re error on column headers - that is an embarrassing Duh! for me I will post a fix withing a few minutes - sorry!

re retirement limit I will add that at the same time.

**Comment by denslowm** [comment] 2019-05-31 20:45
This is really great progress, I am very thankful for your help. 

As a reminder, we had the Completed Page on NfN, so we could look to see how that was done if needed. Let's see what Adam thinks first.

**Comment by adammcmaster** [comment] 2019-06-03 10:47
I'm afraid I'm not sure what to suggest about the dates. As far as I know we're not storing anything other that what's [listed in the API](https://panoptes.docs.apiary.io/#reference/workflows/workflow) so `created_at` and `finished_at` might be the best we can do.

**Comment by PmasonFF** [comment] 2019-06-03 16:48
Given a list of workflows (which we have) we could retrieve the classifications for those workflows and run some sort of classifications per hour (or day) rate to look for a launch window where that metric would first jump.  This would be sloooowwwwww, remain somewhat fuzzy (sorting out beta testing), and something one would run once and record the value somewhere in a file for future use.
Depends on how bad you want it!
Similarly a better finished date would be the latest retirement date any of the subjects in the subject sets and workflows for the projects you are interested in....  Again a bit of a bear to get but as a once off is definitely possible.

**Comment by denslowm** [comment] 2019-06-03 16:51
Let me check with Mark who wrote the Completed page...

**Comment by denslowm** [comment] 2019-06-06 21:14
Hi All,

So it turns out the missing values for `finished_at` predate that data being available (apparently implemented January, 2017). That is to say that script is doing it's job, it's just that those values aren't available via the API.

Another request. Is it possible to include the date of the first classification for a given workflow? That could be a good proxy for the start of an expedition as well.

Thanks again.

**Comment by PmasonFF** [comment] 2019-06-07 01:40
As I said above this is possible, even a more nuanced approach looking for a jump in the classification rate that would signal a launch of a workflow.  It will be slow - effectively requiring a classification export but it only needs to be done once and we can keep the results in a file for future use/merge with the other stats. 
I can write a script, but I can not run it for you as it will need collaborator status to get the classifications.  I will assume that most workflows have had an export generated at some time - and simply look for the last export and use that - it will have the early records which is what I need to look at. If there has been no export I will, for now just build a list of those cases for which we would need to generate an export  (and wait for it to be produced). I can build and test the script on my own test bed project, or one of the projects I do have status on.  Likely next week given the current stuff I have promised. I can get the list of workflows except those for project 9275 which is private and I can not query. If you could send me those I will add them to the list of workflows we want dates for.
Peter

**Comment by PmasonFF** [comment] 2019-06-07 01:42
Oh!,  and a new one project 9356

**Comment by camallen** [comment] 2019-06-07 09:37
`finished_at` records the time all data on a workflows is retired. This changes frequently as new data is added / removed from a worklfow.

> Is it possible to include the date of the first classification for a given workflow? That could be a good proxy for the start of an expedition as well.

I completely agree with Peter, this information is available in your classification or subject exports. Once derived it can be stored and combined for your offline use-case.

**Comment by denslowm** [comment] 2019-06-07 12:25
Peter -- Let's hold off on that approach for now as I think it makes things more complicated and requires another data source. 

Does anyone know what `updated_at` is? I don't see it defined in link that Adam sent.

**Comment by camallen** [comment] 2019-06-07 12:34
`updated_at` is the last time a workflow's data was changed, either internally via Zooniverse systems or externally from an authenticated and authorized user (i.e. via the lab).

From the docs at https://panoptes.docs.apiary.io/#reference/workflows/workflow
`id, created_at, updated_at, workflow_version, content_language, and classifications_count are assigned by the API`

`finished_at is set by the API to a date/time when all subjects for this workflow have been retired.`

**Comment by lcjohnso** [comment] 2020-04-17 03:53
Closing this.

Noting that working, expanded script is available here:
https://github.com/PmasonFF/Zooniverse-data-digging/blob/master/Panoptes_client_examples/org_workflow_stats_expanded.py

**Closed by lcjohnso** 2020-04-17 03:53 UTC
